
// STACK IS A SEQUENTIAL COLLECTION OF ELEMENTS IN SUCH A WAY THAT THAT, THE LAST ELEMENT INSERTED WILL THE FIRST TO BE REMOVED
// IT IS A ABSTRACT DATA TYPE. IT IS DEFINED BY ITS BEHAVIOUR RATHER THAN A MATHERMATICAL MODEL

// EXAMPLE:- IN A STACK OF PLATES, THE PLATE WHICH IS ON TOP OF STACK WILL BE REMOVED FIRST


// STACK USAGE

// BROWSER TRACKING
// UNDO IN SO MANY APPLICATIONS
// CALL STACK IN JAVASCRIPT RUNTIME




