
// QUEUE

// QUEUE IS A SEQUENTIAL COLLECTION OF ELEMENTS WITH FOLLOWS A PRINCIPAL OF FIRST IN AND FIRST OUT 
// IT IS A ABSTRACT DATA TYPE. IT IS DEFINED BY ITS BEHAVIOUR RATHER THAN A MATHERMATICAL MODEL

// EXAMPLE:- PEOPLE WHO WAITING IN A QUEUE AND WHOEVER GOT THEIR ORDER THEY'LL COME OUT OF THE QUEUE


// QUEUE USAGE

// PRINTERS
// CPU TASK SCHEDULING
// CALLBACK QUEUE IN JAVASCRIPT RUNTIME


