

// CIRCULAR QUEUE

// THE SIZE OF THE QUEUE IS FIXED AND A SINGLE BLOCK OF MEMORY IS USED AS IF THE FIRST ELEMENT IS CONNECTED TO THE LAST ELEMENT

// USAGE

// CLOCK
// STREAMING DATA
// TRAFFIC LIGHTS